TestCarPhoneNumbers/Controllers/DependenceFinderController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;
using TestCarPhoneNumbers.Models;

namespace TestCarPhoneNumbers.Controllers
{
    public class DependenceFinderController : Controller
    {
        private readonly ApplicationContext context;

        public DependenceFinderController(ApplicationContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NumbersShower() 
        { 
            if (TempData["NumbersToShow"] is string json)
            {
                var numbers = JsonSerializer.Deserialize<List<NumberToShow>>(json);
                ViewData["NumbersToShow"] = numbers;
            }
            ViewBag.CarNumber = TempData["CarNumber"];
            ViewBag.FailReason = TempData["FailReason"];
            return View(); 
        }

        [HttpPost]
        public IActionResult FindNumbers(string number)
        {
            try
            {
                TempData["CarNumber"] = number;
                List<NumberToShow> numbers = new List<NumberToShow>();
                var car = context.cars.FirstOrDefault(x => x.Number == number);
                if (car == null) 
                {
                    TempData["FailReason"] = "Номер в базе не найден";
                    return Json(new { status = true, message = "Номер в базе не найден", redirectUrl = Url.Action("NumbersShower") });
                }
                Guid carId = car.Id;
                var dependenciesWithCarId = context.dependencies.Where(x => x.CarId == carId && x.IsActive).ToList();
                if (dependenciesWithCarId.Count == 0) 
                {
                    TempData["FailReason"] = "К данному номеру машины не привязан ни один телефон";
                    return Json(new { status = true, message = "Номер найден в базе, но к нему не привязан ни один телефон", redirectUrl = Url.Action("NumbersShower") });
                }
                foreach(var dep in dependenciesWithCarId)
                {
                    var phoneId = dep.PhoneId;
                    if (phoneId == Guid.Empty)
                    {
                        continue;
                    }
                    var phone = context.phones.FirstOrDefault(x => x.Id == phoneId && x.IsActive);
                    if (phone == null)
                    {
                        continue;
                    }
                    NumberToShow newNumber = new NumberToShow();
                    newNumber.Number = phone.Number;
                    newNumber.CreationDate = dep.CreationDateTime;
                    newNumber.IsOwner = dep.IsOwner;
                    numbers.Add(newNumber);
                }
                TempData["NumbersToShow"] = JsonSerializer.Serialize(numbers);
                return Json(new { status = true, message = "Номера найдены", redirectUrl = Url.Action("NumbersShower") });
            }
            catch (Exception ex) 
            { 
                return Json(new { status = false, message = ex.Message }); 
            }
            
        }
    }
}

TestCarPhoneNumbers/Controllers/DependenceRegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Data.Models;
using System;
using Data;

namespace TestCarPhoneNumbers.Controllers
{
    public class DependenceRegisterController : Controller
    {
        private readonly ApplicationContext context;

        public DependenceRegisterController(ApplicationContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        //все методы с телефонным номером

        public IActionResult PhoneAdding()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddPhone(string number)
        {
            try
            {
                var phones = context.phones.ToList();
                bool alreadyExists = phones.Where(x => x.Number == number).Any();
                if (alreadyExists)
                {
                    return Json(new { status = false, message = "Номер уже в базе" });
                }
                context.phones.Add(new Phone { Id = Guid.NewGuid(), Number = number, IsActive = true });
                await context.SaveChangesAsync();
                return Json(new { status = true, message = "Номер добавлен" });
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = ex.Message });
            }
            
        }

        public IActionResult GetAllPhones()
        {
            var phones = context.phones.ToList(); 
            return Json(phones);
        }

        //все методы с номером машины

        public IActionResult CarAdding()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddCar(string number)
        {
            try
            {
                var cars = context.cars.ToList();
                bool alreadyExists = cars.Where(x => x.Number == number).Any();
                if (alreadyExists)
                {
                    return Json(new { status = false, message = "Номер уже в базе" });
                }
                context.cars.Add(new Car { Id = Guid.NewGuid(), Number = number, CreationDateTime = DateTime.UtcNow, IsActive = true });
                await context.SaveChangesAsync();
                return Json(new { status = true, message = "Номер добавлен" });
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = ex.Message });
            }

        }

        public IActionResult GetAllCars()
        {
            var cars = context.cars.ToList();
            return Json(cars);
        }

        //все методы с Зависимостями

        public IActionResult DependenceAdding()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddDependence(string phone, string car, bool isOwner=false)
        {
            try
            {
                var phones = context.phones.ToList();
                var cars = context.cars.ToList();
                var dependences = context.dependencies.ToList();

                bool flagOwnerExists = false;

                var phoneObj = phones.FirstOrDefault(x => x.Number == phone);
                var carObj = cars.FirstOrDefault(x => x.Number == car);
                if (carObj == null) 
                {
                    await AddCar(car);
                    cars = context.cars.ToList();
                    carObj = cars.FirstOrDefault(x => x.Number == car);
                }
                if (phoneObj == null)
                {
                    await AddPhone(phone);
                    phones = context.phones.ToList();
                    phoneObj = phones.FirstOrDefault(x => x.Number == phone);
                }


                if (carObj == null || phoneObj == null)
                {
                    return Json(new { status = false, message = "Ошибка добавления в базу" });
                }

                Guid phoneId = phoneObj.Id;
                Guid carId = carObj.Id;

                if (phoneId == Guid.Empty || carId == Guid.Empty) 
                {
                    return Json(new { status = false, message = "Ошибка записи номера в базе" });
                }

                if (isOwner)
                {
                    foreach (var c in dependences.Where(x => x.CarId == carId))
                    {
                        if (c.IsOwner)
                        {
                            flagOwnerExists = true;
                            break;
                        }
                    }
                    if (flagOwnerExists)
                    {
                        return Json(new { status = false, message = "Владелец авто уже указан" });
                    }
                }

                context.dependencies.Add(new Dependence { Id = Guid.NewGuid(), CarId = carId, PhoneId = phoneId, IsActive = true, IsOwner = isOwner, CreationDateTime = DateTime.UtcNow });
                await context.SaveChangesAsync();

                return Json(new { status = true, message = "Номера связаны" });
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = ex.Message });
            }

        }

        public IActionResult GetAllDependencies()
        {
            var dependences = context.dependencies.ToList();
            return Json(dependences);
        }

    }
}

TestCarPhoneNumbers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Поиск телефонов по номеру машины</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestCarPhoneNumbers.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Домашнаяя страница</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DependenceRegister" asp-action="Index">Добавить машину/телефон или связать их</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DependenceFinder" asp-action="Index">Найти телефон по номеру машины</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TestCarPhoneNumbers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"></script>

    <script src="~/js/DependenceRegister.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>